### ISSUE TITLE
[Question] Passing Arguments

### ISSUE THREAD

**Issue by gavinvonk** [macdja38/minecraft-jsonapi#1]
How would I be able to pass arguments into a request?
`const resultPromise = minecraft.add(call).dispatch(options);`
Do I add an array or something?

**Comment by gavinvonk** [comment]
Solved,
`const resultPromise = minecraft.add(call, [arg]).dispatch(options);`
Worked for me.

**Comment by macdja38** [comment]
Hi, sorry to hear it was not immediately clear, I've created some documentation that should be helpfull when attempting to use this module. 
https://macdja38.github.io/minecraft-jsonapi/
If you have any questions and want to ask me I'm macdja38#7770 on discord and almost always respond within about 8h.

If you encounter any more issues with this repo feel free to let me know. Just to warn you the follow thing for event streams does not yet auto reconnect. Hopefully I'll get a chance to correct that soon.
